version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 30
  assignees:
  - TemaSM
  labels:
  - "Type: Maintenance"
  - dependencies
  versioning-strategy: increase
